# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

leapfrog_cpp <- function(m, i, trajectory_length, stepsize, v_loc_old, v_scale_old) {
    .Call(`_asp24hmc_leapfrog_cpp`, m, i, trajectory_length, stepsize, v_loc_old, v_scale_old)
}

log_acceptance_criterion <- function(prev_x, Impulse_old, x, v, m) {
    .Call(`_asp24hmc_log_acceptance_criterion`, prev_x, Impulse_old, x, v, m)
}

hmc_sampler <- function(m, i, trajectory_length, stepsize) {
    .Call(`_asp24hmc_hmc_sampler`, m, i, trajectory_length, stepsize)
}

build_chain_cpp <- function(m, stepsize, trajectory_length, chain_length, burn_in, thin) {
    .Call(`_asp24hmc_build_chain_cpp`, m, stepsize, trajectory_length, chain_length, burn_in, thin)
}

grad_ll_cpp <- function(beta, gamma, m, type) {
    .Call(`_asp24hmc_grad_ll_cpp`, beta, gamma, m, type)
}

